os: linux
language: node_js
notifications:
  slack:
    template:
      # This template config somehow breaks yaml syntax
      # in the editor although it is valid yaml syntax
      - "Project: lyne-icons"
      - "Build: <%{build_url}|%{build_number}>"
      - "Commit: <%{compare_url}|%{commit}>"
      - "Author: %{author}"
      - "Result: %{result} in %{duration}"
    secure: iazEW2+X7BOdDG09FPmoM4lN+WhNbzMTvuxaSHohL1hlZjuFJMSYyscnF0zkQIoxha68b8RSG+o2xWG9PejS/TfFj9VhsaFDWx+Tybtt2cT6163hObeo0BRBwO8+0FzQ9XJqLvqevU86FwUYbwK9S+shKzH8GcI/sv+m55QcChHLvpKQrWEprKuPnMu8id2eVftpD8pUSVVyiGJe1zQ68Vn0evhVfUzTtQxzDhksyvhbWAwqKxrWt9UvYPG6A9a4a1dUZ1QgDTevLkrh1ZJ5ni0t7dnVIaLcQN2zQ2DGE+vc68i9jlay6uV+Qa8xbFvmdGT8kktIaoocXc+htLZ8dzQdYilASH4eHxguWMmWUPwhaNHdoAhAKFZ3CLLH8IIG7lNd73r/Hk2E3aqzmUnKFyvyNX4eu2/IT0gEiz0Uy9v9+1UsZYLXA4lqTH/jfzBAY569/ZC9w6TuyC0zGB8l1eLkbHff9/ojZ1gk4RdPCFwl2TpIVFx9WZ32BXC24icsr43Ayt7+hUNDGHJ8ykoyzB1jP5+sHbyPLKTokW7D7BQPiz0NpY+ipP3jqvcL/I3bPVg709ghabS1ooAp2RveMEkC0Ld/i6FGGPdBj3TdDxuyNyQZGMJWnfmZjAJ7oUMdi8zCSgrMyiGljHEU7k+ALYowGjti7VtUJTo/LhP9C7Q=
jobs:
  include:
    - stage: build and deploy icons for master
      if: ((branch = master AND type != pull_request) AND fork = false)
      script:
      - npm run lint || travis_terminate 1
      - npm run icons:extract || travis_terminate 1
      - node ./ci/gitPushProperties.js -i "$TRAVIS_BUILD_ID" || travis_terminate 1

      after_success:
      - npm run semantic-release || travis_terminate 1
      - node ./ci/triggerLyneComponents.js -i "$TRAVIS_BUILD_ID" -j $(< .version) || travis_terminate 1

      # prepare git for pushes
      - git remote set-url origin https://lyne-design-system:$GH_TOKEN@github.com/lyne-design-system/lyne-icons.git || travis_terminate 1
      - ./ci/deploy_cdn_assets.sh || travis_terminate 1

    - stage: build and deploy icons for branches other than master
      if: ((branch != master OR type = pull_request) AND fork = false)
      script:
      - npm run lint || travis_terminate 1
      - npm run icons:extract || travis_terminate 1
